### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by spl0i7** [DhavalKapil/icmptunnel#12]
After compiling and executing 
```
# ./icmptunnel
```
I am getting segmentation fault. Tested this on both debian 8 and ubuntu 14.04 and both give same error.

**Comment by DhavalKapil** [comment]
I haven't yet added checks for parameters. This is not how it should be run. See the Readme once.

**Comment by jjungo** [comment]
Do you want a PR for that (without getopt)?

**Comment by DhavalKapil** [comment]
Why do you think `getopt` should not be used?

**Comment by jjungo** [comment]
In this case, I think it's like using a bazooka for killing a bee...

**Comment by DhavalKapil** [comment]
:+1: Fine with me
