### ISSUE TITLE
Unable to write to tunnel

### ISSUE THREAD

**Issue by spl0i7** [DhavalKapil/icmptunnel#14]
So , I was playing around this tool but I could not get it started on a vps because program exited saying 
Unable to write to tunnel : Invalid argument. Here's a screenshot to illustrate the issue
![Issue](https://cloud.githubusercontent.com/assets/6875910/13545536/72696ada-e2b5-11e5-9945-91a9badfb2fb.PNG)
I used Arch Linux here but I had same issue with debian 8

**Comment by spl0i7** [comment]
It's a problem with monitoring service which sends ICMP packets to check if server is up , temporary solution is to drop ICMP packets from that IP. Is there any permanent fix ? can we recognize our icmp tunnel packet and differentiate it from normal ICMP requests?

**Comment by DhavalKapil** [comment]
Yup this issue is to be taken care of in #5. Unfortunately, I cannot find time to work further on it presently. Probably will address it in some time.
