### ISSUE TITLE
compiling on Cygwin

### ISSUE THREAD

**Issue by supersophie** [DhavalKapil/icmptunnel#19]
Hi,  Could this compile on Cygwin?

**Comment by DhavalKapil** [comment]
I am not sure about it. icmptunnel uses a lot of 'low level' functions so I think it may not compile on Windows. Anyways if you are able to run it using Cygwin, do let me know :)

**Comment by hxhxd** [comment]
@supersophie 
Hi, How's it going of your compile on Cygwin? 
-- I tried but got many "invalid application of" and "declared inside parameter list" kindda errors.
If you get it compiled through, could you share your experience with us?
Thanks!

**Comment by supersophie** [comment]
Hi guys, I have up !  Merry Christmas.
Sophie

Donate 5€ a month to HELP CHILDREN LIVE in Syria.
http://www.msf.org/en/donate
Medicine sans Frontiers
