### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by ghost** [DhavalKapil/icmptunnel#27]
deleted

**Comment by buddy-yao** [comment]
@ldaochen alternatively, u could think about  ss + kcptun. 
if your udp tunnel was restricted by isp, u could think about ss + kcptun + udp2raw-tunnel.
wonderful gfw!

**Comment by iceonsun** [comment]
我来自卖自夸，安利一发：rsock，kcptun伴侣，支持linux/mac平台，能达到kcptun速度的70%-90%。
https://github.com/iceonsun/rsock

**Comment by sleshep** [comment]
i tested on vultr japan, it seems that drop a lot of packet, but vultr LA have stable network and less drop packet behavior,so i suggest u use vultr-LA on America.
i test network bandwidth by `iperf3 ` you can simply install it on ubuntu by command`apt install iperf3`

**Comment by iceonsun** [comment]
You can try kcptun+rsock for once. It runs on faketcp. No iptable operations invoved.

https://github.com/iceonsun/rsock
