### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [DhavalKapil/icmptunnel#6]
Would you like to [add more error handling](https://github.com/DhavalKapil/icmptunnel/blob/e26370a55b5c3a93eb5ef94e73c2d3a6374228ce/icmp.c#L139 "Update candidate: receive_icmp_packet()") for return values from [functions like "malloc"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation")?

**Comment by DhavalKapil** [comment]
It's always good to make code error prone. I'd prefer adding.

**Comment by DhavalKapil** [comment]
I'm satisfied with current state of code. If you would like to add anything do feel free.
